version: '3.8'

services:
  redirection-page:
    image: nginx:alpine
    container_name: redirection_educative
    ports:
      - "8090:80"  # Choisis un port libre
    volumes:
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
