services:
  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    restart: unless-stopped
    ports:
      - "3333:3333"  # Admin panel (https)
      - "8080:80"    # Phishing page (http)
